### PR TITLE
Fix super+enter behavior (fixes #72)

### LINKED ISSUE #72: Cmd+Return behaves unexpectedly (w/o semicolons)
Using Sublime Text 2, `Cmd+Shift+Return` from anywhere on a line works as expected: it enters a new line just above the current line, indented at the current line’s level. But when I use `Cmd+Return` from anywhere on a line, I get this:

- a new space is entered at the end of the current line,
- a new line, with an added level of indentation is created below the current line,
- an additional line, at the current line’s indentation level, is created below the line just created,
- the cursor is on the extra-indented line.

This only happens when the line from which the keystroke is used does not have a semicolon at the end. When a semicolon is present, the same command behaves as expected. See this GIF for an illustration of the problem.

GIF illustrating the problem

What I expect from `Cmd+Return` is the opposite of `Cmd+Shift+Return`: it enters a new line just below the current line, indented at the current line’s level.

### PR DESCRIPTION
**Pull request by agarzola**
This addresses the problem described in #72.

### CODE REVIEW

**Comment by grassator** [comment]
I have just installed the fresh copy of sublime text and the master of Stylus plugin and I can't actually reproduce the original bug you described. Could you please let me know which plugins do you have besides Stylus?

**Comment by agarzola** [comment]
Probably too many. Here’s the result of running `ls` on my Packages directory.
```
0_package_control_loader
ASP
ActionScript
AppleScript
Batch File
C#
C++
CSS
Clojure
Color Scheme - Default
D
Dayle Rees Color Schemes
Default
Diff
EJS
Emmet
EncodingHelper
Erlang
FakeDataGenerator
FakeImg Image Placeholder Snippet
Figlet Big ASCII Text
GitGutter
GitHub Flavored Markdown Preview
Go
Graphviz
Groovy
HTML
HTMLBeautify
Haml
Handlebars
Haskell
Hayaku - tools for writing CSS faster
JSHint Gutter
Jade
Java
JavaScript
JavaScriptNext - ES6 Syntax
LESS
LaTeX
Language - English
Lisp
Logs Colorize
Lua
Makefile
Markboard
Markdown
Markdown Preview
MarkdownEditing
Matlab
OCaml
Objective-C
Origami
PHP
Package Control
PackageDev
Perl
PyV8
Python
R
Rails
Regular Expressions
RestructuredText
Ruby
Ruby Slim
SQL
Sass
SassBeautify
Scala
Schemr
ShellScript
Six - Future JavaScript Syntax
Stylus
SyncedSideBar
Syntax Highlighting for Sass
TCL
Text
Textile
Theme - Afterglow
Theme - Aqua
Theme - Default
Theme - Farzher
Theme - Nexus
Theme - Spacegray
Themr
Tomorrow Color Schemes
Unquote
User
Velocity
Vintage
XML
YAML
bz2
caniuse_local
ordereddict
pygments
pyyaml
```

**Comment by grassator** [comment]
If you have time and access to some VM or are ok temporarily replace your packages folder could you please confirm that the error actually happens on sublime text 2 without any packages besides Stylus.

Since I can't confirm the bug I'm a bit hesitant to merge this.

**Comment by agarzola** [comment]
You are correct. With only the core packages and the Stylus package, this issue does not occur.

Thank you for pointing me in the right direction! I always thought it had to do with Stylus package since it’s the only syntax with which I’ve observed this bizarre behavior. I’ll close this pull request, nail down where the conflict is occurring and report any findings in #72.

Thanks again!

**Pull request closed without merging**
